script:
  - mkdir build
  - protoc --proto_path=src --python_out=build src/*
before_script:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xzvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1.tar.gz && ./configure --prefix=/usr && make && sudo make install
